spring.application.name=nb-assistant-ai

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nb_assistant
spring.datasource.username=nb_admin
spring.datasource.password=nb_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Storage
storage.provider=${STORAGE_PROVIDER:local}

# Gemini Chat
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
spring.ai.google.genai.project-id=${SPRING_AI_GOOGLE_GENAI_PROJECT_ID:nb-assistant-ai}
spring.ai.google.genai.location=${SPRING_AI_GOOGLE_GENAI_LOCATION:us-central1}

# Embeddings
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}
spring.ai.google.genai.embedding.project-id=${spring.ai.google.genai.project-id}
spring.ai.google.genai.embedding.location=${spring.ai.google.genai.location}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-2
spring.ai.google.genai.embedding.text.options.dimensions=768

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.index-type=HNSW

oci.objectstorage.namespace=${OCI_NAMESPACE}
oci.objectstorage.bucket-name=nb-assistant-documents
oci.objectstorage.region=sa-saopaulo-1
oci.config.file=${OCI_CONFIG_FILE:~/.oci/config}
oci.config.profile=DEFAULT


oci.tenancy-id=${OCI_TENANCY_ID}
oci.user-id=${OCI_USER_ID}
oci.fingerprint=${OCI_FINGERPRINT}
oci.private-key-path=${OCI_PRIVATE_KEY_PATH}
oci.region=${OCI_REGION}
oci.namespace=${OCI_NAMESPACE}
oci.bucket-name=${OCI_BUCKET_NAME}
oci.compartment-id=${OCI_COMPARTMENT_ID}